# Inventory file for EC2 instances
[ec2_servers]
# ระบุ IP หรือ DNS ของ EC2 แต่ละเครื่อง
ec2-node-01 ansible_host=192.168.1.100 ansible_user=ubuntu
# ec2-node-02 ansible_host=192.168.1.101 ansible_user=ec2-user

[ec2_servers:vars]
# กำหนด path ของ SSH private key สำหรับเครื่อง Ansible ใช้ connect เข้า EC2 ในครั้งแรก
ansible_ssh_private_key_file=~/.ssh/your-initial-ec2-key.pem
ansible_python_interpreter=/usr/bin/python3
